# Custom Language File for Launcher Customizer

[ejs.app]
title = "Ratel Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/hd9TjGpHge"

[ejs.settings]
sourceGithubLink = "https://github.com/Kainius/RatelLauncher"
supportLink = "https://github.com/Kainius/RatelLauncher/issues"

[ejs.welcome]
welcomeHeader = "라텔 힐링캠프에 오신 것을 환영합니다"
welcomeDescription = "라텔 멤버들에게 제공되는 전용 서버입니다"
welcomeDescCTA = "라텔 힐링캠프까지 몇 번의 클릭만이 남았습니다."
